### PR TITLE
Update select component for searching

### PR DESCRIPTION
**Pull request by samely**
### Context
Current `result geocoder dropdown` doesn't allow to navigate between options.
This PR add `multiselect` as the drop-down for easy navigation.

### Changes
:heavy_check_mark: Replaced `input` with a `<multiselect>` vue.js component for `geocoder results`
:heavy_check_mark: Integrated icons to the new component according to the result list dynamically by using slots
:heavy_check_mark: Set listener to 'multiselect' `DOM` change, so no need to use `mouse` and `key` events.
:heavy_check_mark: Set pointer in search input box.

@ingalls @Fa7C0n @ianshward

### CODE REVIEW

**Comment by ingalls** [comment]
Just a couple small things,

Can we isolate the icon in the drop down like the current version?

screenshot from 2018-09-25 08-08-29

When you click on a Search result with a lot of text, it messes up the top bar:
screenshot from 2018-09-25 08-11-17

**Comment by ingalls** [comment]
Hey @samely if you get a little free time to fix the last remaining blockers would love to get this merged!

**Comment by samely** [comment]
Thanks for reminded me this! And thanks for the feedback. I will take a look and finish it!

**Comment by samely** [comment]
:wave: @ingalls could you check this once more? :pray:

**Comment by ingalls** [comment]
Thanks for taking another look at this!

Can we fix the style here to have the same padding/margins on the bottom as the top?
screenshot from 2018-11-21 07-45-25

Can the dropdown be closed when you initially open the page?
screenshot from 2018-11-21 07-46-56

The text in the search box disappears when you click away from the dropdown. It's still there but you have to click back in the search box to see it! Is it possible to fix this?
screenshot from 2018-11-21 07-47-53
screenshot from 2018-11-21 07-47-48

Most importantly, I <3 the changes you made, it looks really really good! Excited to get this merged!

**Comment by samely** [comment]
> The text in the search box disappears when you click away from the dropdown. It's still there but you have to click back in the search box to see it! Is it possible to fix this?

@ingalls do you mean to keep the dropdown active even if you click away from the search box?

> Most importantly, I <3 the changes you made, it looks really really good! Excited to get this merged!

:heart:

**Comment by samely** [comment]
:taco:

**Pull request merged**
